version: '3'

services:
  db:
    image: mysql:8.0.21
    ports:
      - "30000:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: flask
    volumes:
      - ./db:/docker-entrypoint-initdb.d/:ro